//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSalesSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_PAYMENT_DETAIL
    {
        public string PM_ID { get; set; }
        public string EMP_ID { get; set; }
        public System.DateTime PAY_DATE { get; set; }
        public decimal AMOUNT { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
